disp('*** aufgabe 1');
clear

disp( '9 + 0*x - 10*x^2 + 0*x^3 + 1*x^4' );
disp ([ 'laenge der vektoren bestimmen und abspeichern' ...
'n-fache replizierung des vektors x in einer matrix A' ...
'erzeugung der Matrix B, welche die Potenzen enthaelt' ...
'stellenweises potenzieren der eintraege von A mit B und somit erzeugung der einzelnen potenzterme' ...
'multiplizierung mit dem vektor a, fuer die auswertung der einzelnen polynom-werte pro x-wert' ]);
